MAIN_WINDOW_SIZES = MAIN_WINDOW_WIDTH, MAIN_WINDOW_HEIGHT = 800, 600

MAIN_TITLE_SIZES = MAIN_TITLE_WIDTH, MAIN_TITLE_HEIGHT = 300, 50
MAIN_TITLE_FONT = ("Times", "19", "bold")

IMG_CHOOSING_SIZES = IMG_CHOOSING_WIDTH, IMG_CHOOSING_HEIGHT = 300, 120
IMG_CHOOSING_COORDS = 50, 45
IMG_CHOOSING_FONT = ("Times", "13")
IMG_CHOOSING_NAME_FONT = ("Arial", "10")
IMG_CHOOSING_BTN_FONT = ("Times", "13")

FRAME_ANALYSIS_SIZES = FRAME_ANALYSIS_WIDTH, FRAME_ANALYSIS_HEIGHT = 300, 120
FRAME_ANALYSIS_COORDS = 400, 45
FRAME_ANALYSIS_BTN_FONT = ("Times", "13")

FRAME_RESULTS_SIZES = FRAME_RESULTS_WIDTH, FRAME_RESULTS_HEIGHT = 300, 295
FRAME_RESULTS_COORDS = 400, 225
FRAME_RESULTS_TITLE_FONT = ("Times", "13")
FRAME_RESULTS_MAIN_FONT = ("Times", "11")
FRAME_RESULTS_EXTRACTED_FONT = ("Times", "10")

IMG_PREVIEW_SIZES = IMG_PREVIEW_WIDTH, IMG_PREVIEW_HEIGHT = 300, 300
IMG_PREVIEW_COORDS = 50, 220
IMG_PREVIEW_INFO_FONT = ("Times", "10")

WAITING_FRAME_SIZES = WAITING_FRAME_WIDTH, WAITING_FRAME_HEIGHT = MAIN_WINDOW_WIDTH - 200, 100
WAITING_FRAME_COORDS = 100, 170
WAITING_FONT = ("Times", "14", "bold")
WAITING_GIF_SIZES = WAITING_GIF_WIDTH, WAITING_GIF_HEIGHT = 40, 40
WAITING_GIF_COORDS = 100, 25
