STEGO_WINDOW_SIZES = STEGO_WINDOW_WIDTH, STEGO_WINDOW_HEIGHT = 600, 400

STEGO_IMG_CHOOSING_SIZES = STEGO_IMG_CHOOSING_WIDTH, STEGO_IMG_CHOOSING_HEIGHT = 560, 70
STEGO_IMG_CHOOSING_COORDS = 10, 10
STEGO_IMG_CHOOSING_FONT = ("Times", "12")
STEGO_IMG_CHOOSING_NAME_FONT = ("Arial", "10")
STEGO_IMG_CHOOSING_BTN_FONT = ("Times", "12")

FRAME_DEC_SETTINGS_SIZES = FRAME_DEC_SETTINGS_WIDTH, FRAME_DEC_SETTINGS_HEIGHT = 560, 220
FRAME_DEC_SETTINGS_COORDS = 10, 90

FRAME_LSB_SIZES = FRAME_LSB_WIDTH, FRAME_LSB_HEIGHT = FRAME_DEC_SETTINGS_WIDTH // 2 - 20, FRAME_DEC_SETTINGS_HEIGHT - 10
FRAME_LSB_COORDS = 0 + 10, 5

FRAME_KZ_SIZES = FRAME_KZ_WIDTH, FRAME_KZ_HEIGHT = FRAME_LSB_SIZES
FRAME_KZ_COORDS = FRAME_DEC_SETTINGS_WIDTH // 2 + 10, 5

BTN_DECRYPT_SIZES = BTN_DECRYPT_WIDTH, BTN_DECRYPT_HEIGHT = 300, 50
BTN_DECRYPT_COORDS = 130, 320
BTN_DECRYPT_FONT = ("Times", "12")

DEC_LSB_BTN_FONT = ("Arial", "14")
DEC_LSB_DIRECT_BTN_FONT = ("Arial", "10")
DEC_LSB_RND_BTN_FONT = ("Arial", "10")

DEC_LSB_BTN_SIZES = DEC_LSB_BTN_WIDTH, DEC_LSB_BTN_HEIGHT = 180, 25
DEC_LSB_BTN_COORDS = 40, 5

DEC_LSB_DIRECT_BTN_SIZES = DEC_LSB_DIRECT_BTN_WIDTH, DEC_LSB_DIRECT_BTN_HEIGHT = 123, 25
DEC_LSB_DIRECT_BTN_COORDS = 5, 35

DEC_LSB_RND_BTN_SIZES = DEC_LSB_RND_BTN_WIDTH, DEC_LSB_RND_BTN_HEIGHT = 123, 25
DEC_LSB_RND_BTN_COORDS = 132, 35

DEC_KZ_BTN_FONT = ("Arial", "14")
DEC_KZ_DIRECT_BTN_FONT = ("Arial", "10")
DEC_KZ_RND_BTN_FONT = ("Arial", "10")

DEC_KZ_BTN_SIZES = DEC_KZ_BTN_WIDTH, DEC_KZ_BTN_HEIGHT = 180, 25
DEC_KZ_BTN_COORDS = 40, 5

DEC_KZ_DIRECT_BTN_SIZES = DEC_KZ_DIRECT_BTN_WIDTH, DEC_KZ_DIRECT_BTN_HEIGHT = 123, 25
DEC_KZ_DIRECT_BTN_COORDS = 5, 35

DEC_KZ_RND_BTN_SIZES = DEC_KZ_RND_BTN_WIDTH, DEC_KZ_RND_BTN_HEIGHT = 123, 25
DEC_KZ_RND_BTN_COORDS = 132, 35

STEGO_LSB_PARAMS_ENTRY_FONT = ("Arial", "12")
STEGO_LSB_PARAMS_ENTRY_SIZES = STEGO_LSB_PARAMS_ENTRY_WIDTH, STEGO_LSB_PARAMS_ENTRY_HEIGHT = 90, 25

STEGO_LSB_PARAMS_TEXT_FONT = ("Times", "11")
STEGO_LSB_PARAMS_TEXTS_SIZES = STEGO_LSB_PARAMS_TEXTS_WIDTH, STEGO_LSB_PARAMS_TEXTS_HEIGHT = 123, 25

STEGO_KZ_PARAMS_ENTRY_FONT = ("Arial", "12")
STEGO_KZ_PARAMS_ENTRY_SIZES = STEGO_KZ_PARAMS_ENTRY_WIDTH, STEGO_KZ_PARAMS_ENTRY_HEIGHT = 90, 25

STEGO_KZ_PARAMS_TEXT_FONT = ("Times", "11")
STEGO_KZ_PARAMS_TEXTS_SIZES = STEGO_KZ_PARAMS_TEXTS_WIDTH, STEGO_KZ_PARAMS_TEXTS_HEIGHT = 123, 25

WAITING_MINI_FRAME_SIZES = WAITING_MINI_FRAME_WIDTH, WAITING_MINI_FRAME_HEIGHT = STEGO_WINDOW_WIDTH - 200, 100
WAITING_MINI_FRAME_COORDS = 100, 130
WAITING_MINI_FONT = ("Times", "13", "bold")
WAITING_MINI_GIF_SIZES = WAITING_MINI_GIF_WIDTH, WAITING_MINI_GIF_HEIGHT = 40, 40
WAITING_MINI_GIF_COORDS = 30, 25
